log_cfg: conf/logging.yaml
log_dir: logs

env:
  name: reacher
  cost:
    clazz: ilqr.costs.QuadraticCost
    params:
      state_position_cost: [500000, 500000]
      state_velocity_cost: [40000, 40000]
      action_cost: [0.003, 0.003]
      target_state: [0, 0, 0, 0]
  render: false

motor_babbling:
  num_trials: 1

time_horizon: 200
num_trials: 1
num_rollouts_per_trial: 1

ilqr:
  max_iter: 20
